---
- name: this playbook uninstall httpd
  hosts: all
  become: true
  tasks:

  - name: Stop httpd service
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: uninstall httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apache service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
